### ISSUE TITLE
Create a Dockerfile to provide a 'containerized' testing environment to developers.

### ISSUE THREAD

**Issue by jasontclark** [MartinCocks/fabric-sdk-rest#4]
In order to provide a way to conduct tests in a self-contained development environment, create a docker container to install and configure the fabric REST API.  This docker container can also be used for deployment testing, unit-tests, and FVT testing.

**Comment by chrispoole643** [comment]
Sounds like a good idea. I'd intended to do this but haven't yet got around to it.

**Comment by ijmitch** [comment]
The plan was always to provide such a package. This is how any service built to include this capability would want to consume it. We have it on the backlog.

**Comment by jasontclark** [comment]
@ijmitch - Received your email.  Perhaps the wording of this issue should be adjusted to "provide a dockerfile inside the fabric-sdk-rest project" as opposed to "Create a docker container", which may imply the creation of public images.  At this point, if it's safe to provide a Dockerfile inside the project, this is the approach I will take.
